server:
  netty:
    connection-timeout: 20s
    idle-timeout: 15s
  shutdown: graceful
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    bootstrap:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      httpclient:
        connect-timeout: 2000 # 2s
        response-timeout: 20s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - SaveSession
        - TokenRelay
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Request-Headers, RETAIN_FIRST
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: elastic-query
          uri: ${ELASTIC_QUERY_SERVICE_URL:http://elastic-query:8080}
          predicates:
            - Path=/elastic-query/**
          filters:
            - RewritePath=/elastic-query/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: queryServiceCircuitBreaker
                fallbackUri: forward:/fallback/query-fallback
        - id: analytics
          uri: ${ANALYTICS_SERVICE_URL:http://analytics:8080}
          predicates:
            - Path=/analytics/**
          filters:
            - RewritePath=/analytics/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: analyticsServiceCircuitBreaker
                fallbackUri: forward:/fallback/analytics-fallback
        - id: kafka-streams
          uri: ${KAFKA_STREAMS_SERVICE_URL:http://kafka-streams:8080}
          predicates:
            - Path=/kafka-streams/**
          filters:
            - RewritePath=/kafka-streams/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: streamsServiceCircuitBreaker
                fallbackUri: forward:/fallback/streams-fallback


  redis:
    connect-timeout: 20s
    host: localhost
    port: 6379
    timeout: 20s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: twitter:gateway

  keycloak:
    server-url: http://keycloak-server:8080
    server-external-url: https://keycloak.greeta.net
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${spring.keycloak.server-external-url}/realms/twitter-realm
          jwk-set-uri: ${spring.keycloak.server-url}/realms/twitter-realm/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: twitter-app
      principal-attribute: preferred_username

twitter-app:
  base-url: https://twitter.greeta.net
  redirect-url: ${twitter-app.base-url}/*

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

logging:
  group:
    circuitbreaker: io.github.resilience4j, org.springframework.cloud.circuitbreaker
  pattern: 
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    net.greeta.twitter: DEBUG
    circuitbreaker: info
    org.springframework.cloud.kubernetes: TRACE
    org.springframework.security: DEBUG

info:
  system: Gateway Service

management:
  endpoints:
    web:
      exposure:
        include: bindings, configprops, env, flyway, functions, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    # groups-order: DESC
    path: /
    config-url: /v3/api-docs/swagger-config
    urls:
      # - url: /v3/api-docs
      #   name: API Gateway Service
      #   primaryName: API Gateway Service
      - url: /elastic-query/v3/api-docs
        name: Elastic Query Service
      - url: /analytics/v3/api-docs
        name: Analytics Service
      - url: /kafka-streams/v3/api-docs
        name: Kafka Streams Service

gateway-service:
  timeout-ms: 3000
  failure-rate-threshold: 50
  slow-call-rate-threshold: 50
  slow-call-duration-threshold: 50
  permitted-num-of-calls-in-half-open-state: 10
  sliding-window-size: 10
  min-number-of-calls: 10
  wait-duration-in-open-state: 60000