name: Production Stage

on:
  repository_dispatch:
    types: [app_delivery]

jobs:
  update:
    name: Update application version
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    env:
      APP_NAME: ${{ github.event.client_payload.app_name }}
      APP_VERSION: ${{ github.event.client_payload.app_version }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Update image version
        run: |
          cd module-app
          sed -i "s/elastic-query-service:.*\"/elastic-query-service:${{ env.APP_VERSION }}\"/" c9-01-elastic-query-service.tf
          sed -i "s/analytics-service:.*\"/analytics-service:${{ env.APP_VERSION }}\"/" c9-02-analytics-service.tf
          sed -i "s/kafka-streams-service:.*\"/kafka-streams-service:${{ env.APP_VERSION }}\"/" c9-03-kafka-streams-service.tf
          sed -i "s/twitter-to-kafka-service:.*\"/twitter-to-kafka-service:${{ env.APP_VERSION }}\"/" c9-04-twitter-to-kafka-service.tf
          sed -i "s/kafka-to-elastic-service:.*\"/kafka-to-elastic-service:${{ env.APP_VERSION }}\"/" c9-05-kafka-to-elastic-service.tf          
          sed -i "s/gateway-service:.*\"/gateway-service:${{ env.APP_VERSION }}\"/" c9-06-gateway-service.tf
      - name: Commit updated manifests
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update ${{ env.APP_NAME }} to version ${{ env.APP_VERSION }}"
          branch: master